name: myneo
favicon: null
layout_spectrum: 0.8835608111694455
typography_spectrum: 0.6732888226397336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aac2b4'
    - '#1c76ca'
    - '#79adc5'
    - '#3899de'
    - '#c8ddca'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
